### ISSUE TITLE
npm run serve error

### ISSUE THREAD

**Issue by Ankor12** [shakhruz/angelfarmers-ui#33]
Hello i have errors when runing npm run serve command

` ERROR  Failed to compile with 10 errors

These dependencies were not found:

* @/../.keys.js in ./src/db.js, ./src/service/dfuseapi.js
* node:buffer in ./node_modules/node-fetch/src/index.js
* node:http in ./node_modules/node-fetch/src/index.js
* node:https in ./node_modules/node-fetch/src/index.js
* node:net in ./node_modules/node-fetch/src/utils/referrer.js
* node:stream in ./node_modules/node-fetch/src/index.js
* node:url in ./node_modules/node-fetch/src/request.js
* node:util in ./node_modules/node-fetch/src/headers.js
* node:zlib in ./node_modules/node-fetch/src/index.js

To install them, you can run: npm install --save @/../.keys.js node:buffer node:http node:https node:net node:stream node:url node:util node:zlib
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'

`

Any idea ?

**Comment by shakhruz** [comment]
yes, 2 things:
1. try using 'yarn' to install and 'yarn serve' to run the app instead of 'npm'
2. add .keys.js file to the project root with credentials for your firebase firestore configuration. The file must include the following lines with filled in data:

export const FB_APIKEY="..."
export const FB_authDomain="..."
export const FB_projectId="..."
export const FB_storageBucket="..."
export const FB_messagingSenderId="..."
export const FB_appId="..."
export const FB_measurementId="..."

**Comment by Ankor12** [comment]
Thank you, it worked, problem solved
